import { COMPANY_ADDRESS } from '@/lib/config';
import { headline, introduction, steps, problems, faqs, type Variant } from './content';
import { Actions, CTA, Icon, Label, Logo } from './Primitives';
import Navigation from './Navigation';
import ProductDemo from './ProductDemo';
function HeroCopy() { return <><Label>AI Workforce for Travel Operations</Label><h1><span>{headline[0]}</span><span><span className="lp-headline-phrase">{headline[1]}</span><span className="lp-headline-phrase">{headline[2]}</span></span></h1><p className="lp-hero-description">{introduction}</p><Actions /><p className="lp-hero-note">まずは、ひとつの業務から。</p></>; }
function WorkJourney() { return <div className="lp-journey-card"><div className="lp-journey-top"><span>FROM BOOKING TO COMPLETION</span><Icon name="arrow"/></div><p className="lp-journey-heading">予約が入る。<br />その先の仕事が、動き出す。</p><ol>{steps.map((s, i) => <li key={s.en}><span className="lp-journey-number">0{i + 1}</span><div><span className="lp-en">{s.en}</span><strong>{s.short}</strong></div><Icon name={s.icon} size={20}/></li>)}</ol><div className="lp-journey-end"><Icon name="check"/><span>Verified Completion</span></div><p className="lp-fineprint">Gappyの実行・確認プロセスを示す概念図</p></div>; }
function Hero({ variant }: {
    variant: Variant;
}) {
    if (variant === 'b')
        return <section className="lp-hero lp-hero-b"><div className="lp-container"><div className="lp-hero-copy"><HeroCopy /></div><div className="lp-product-stage"><aside className="lp-stage-note"><span className="lp-large-number">01</span><h2>予約の先まで、<br />見渡せる。</h2><p>進めるべき仕事と、<br />その判断の根拠をひとつに。</p><span className="lp-stage-line"/></aside><ProductDemo compact/><aside className="lp-stage-proof"><Icon name="check" size={32}/><strong>返事が来た。<br />その次を確かめる。</strong><p>必要な条件と、最新の証拠。<br />両方がそろって、完了へ。</p></aside></div></div></section>;
    return <section className={`lp-hero lp-hero-${variant}`}><div className="lp-container lp-hero-grid"><div className="lp-hero-copy"><HeroCopy /></div><div className="lp-hero-visual">{variant === 'c' ? <WorkJourney /> : <><div className="lp-visual-heading"><span className="lp-dot"/> 予約後の仕事を、完了まで。</div><ProductDemo compact/></>}</div></div><div className="lp-container lp-hero-bottom"><span>JAPAN-FIRST. ASIA-READY.</span><a href="#problem">予約後の仕事を見る <span aria-hidden="true">↓</span></a></div></section>;
}
function Problem() { return <section id="problem" className="lp-section lp-problem"><div className="lp-container"><div className="lp-section-intro"><Label>THE WORK AFTER BOOKING</Label><h2>予約はデジタルに。<br /><span className="lp-heading-phrase">その後の仕事は、</span><span className="lp-heading-phrase">まだ人の手に。</span></h2><p>メール、予約システム、関係者とのやり取り。<br className="lp-desktop-break"/>その間をつなぐ仕事が、現場に残っています。</p></div><div className="lp-problem-grid">{problems.map(([label, title, body, icon], i) => <article key={label}><div className="lp-problem-icon"><Icon name={icon} size={28}/><span>0{i + 1}</span></div><span className="lp-problem-label">{label}</span><h3>{title}</h3><p>{body}</p></article>)}</div><div className="lp-category"><span>Gappy AI Workforce</span><p>企業の複雑な業務を実行するAI。<strong>まずは、旅行の現場から。</strong></p></div></div></section>; }
function StepVisual({ index }: {
    index: number;
}) { return <div className={`lp-step-visual lp-step-visual-${index}`}><span className="lp-overline">{steps[index].tag}</span><div className="lp-mini-flow"><span><Icon name={steps[index].icon} size={32}/></span><i /><span><Icon name={index === 3 ? 'check' : 'arrow'} size={32}/></span></div><strong>{steps[index].detail}</strong><p>{['予約内容と現在の状態を比較', '自動実行の範囲を確認', '実行の結果とやり取りを記録', 'Verified Completion'][index]}</p></div>; }
function Mechanism({ variant }: {
    variant: Variant;
}) { return <section id="mechanism" className={`lp-section lp-mechanism lp-mechanism-${variant}`}><div className="lp-container"><div className="lp-section-intro"><Label>HOW GAPPY WORKS</Label><h2>動かすだけでなく、<br />完了したことまで確かめる。</h2><p>検知、判断、実行、確認。<br />この4つのステップで、予約後の実務を前に進めます。</p></div><ol className="lp-mechanism-steps">{steps.map((s, i) => <li key={s.en}><div className="lp-step-copy"><div className="lp-step-kicker"><span>0{i + 1}</span><span>{s.en}</span></div><h3>{s.title.split("、").map((phrase, index) => <span className="lp-heading-phrase" key={phrase}>{phrase}{index === 0 ? "、" : ""}</span>)}</h3><p>{s.body}</p>{variant !== 'a' && <span className="lp-step-tag">{s.tag}</span>}</div>{variant === 'a' ? <StepVisual index={i}/> : <span className="lp-step-icon"><Icon name={s.icon} size={32}/></span>}</li>)}</ol><div className="lp-mechanism-foot"><p>必要な判断は人へ。結果には、確認できる根拠を。</p><a href="/ja/technology">技術と設計を見る <span aria-hidden="true">↗</span></a></div></div></section>; }
function Proof({ variant }: {
    variant: Variant;
}) { return <section id="proof" className={`lp-section lp-proof lp-proof-${variant}`}><div className="lp-container lp-proof-grid"><div className="lp-proof-copy"><Label>SEE IT IN ACTION</Label><h2>「回答あり」から、<br />「確認済み」へ。</h2><p>ガイドから届いた回答を照合する。予定が変わったら、もう一度確かめる。この画面で、状態の変化をお試しください。</p><ol className="lp-proof-points"><li><span>01</span><div><h3>変化がわかる</h3><p>未完了の仕事と、次に必要な確認を表示。</p></div></li><li><span>02</span><div><h3>根拠が残る</h3><p>回答を必要条件と照合して、完了を判断。</p></div></li><li><span>03</span><div><h3>変更に向き合う</h3><p>以前の確認を見直し、新しい証拠を確認。</p></div></li></ol><p className="lp-proof-disclaimer">既存の公開デモをもとにした説明用UIです。顧客の本番運用や実接続の証明ではありません。</p><a className="lp-text-link" href="/ja/#verification">公開サイトの検証デモを見る <span aria-hidden="true">↗</span></a></div><ProductDemo interactive/></div><div className="lp-container lp-proof-cta"><span>自社の業務では、何から任せられる？</span><CTA location="proof"/></div></section>; }
function GettingStarted() { return <section id="getting-started" className="lp-section lp-start"><div className="lp-container"><div className="lp-section-intro"><Label>START WITH ONE WORKFLOW</Label><h2>まず、ひとつの業務から。<br />無理なく、確かめながら。</h2><p>いまの仕事を理解することから、導入の検討を始めます。</p></div><ol className="lp-start-steps">{[['業務を知る', '確認や変更で手が止まる場面を、具体的にお聞かせください。'], ['任せる範囲を決める', '対象業務、利用システム、人の承認が必要な場面を整理します。'], ['完了条件を確かめる', '何をもって完了とするか、どんな証拠を残すかを一緒に検討します。']].map(([title, body], i) => <li key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></div></section>; }
function FAQ() { return <section id="faq" className="lp-section lp-faq"><div className="lp-container lp-faq-grid"><div><Label>QUESTIONS & ANSWERS</Label><h2>よくあるご質問</h2></div><div>{faqs.map(([q, a]) => <details key={q}><summary><span className="lp-q">Q.</span><span>{q}</span><span className="lp-plus" aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>; }
function FinalCTA() { return <section className="lp-final"><div className="lp-container"><Label>LET’S MOVE WORK FORWARD</Label><h2>旅行を動かす仕事を、<br />次のステージへ。</h2><p>確認・催促・変更対応。<br />あなたの現場に残っている仕事を、お聞かせください。</p><CTA location="final"/><span className="lp-final-note">今のシステムや業務の流れから、ご相談いただけます。</span></div></section>; }
function Footer() { return <footer className="lp-footer"><div className="lp-container"><div className="lp-footer-top"><div><Logo /><p>旅行業界を、AIが働く世界へ。</p><span className="lp-en">Japan-first. Asia-ready.</span></div><nav aria-label="フッターナビゲーション"><div><strong>Gappyを知る</strong><a href="/ja/about">会社情報</a><a href="/ja/technology">技術と設計</a><a href="/ja/travel">旅行業務への取り組み</a></div><div><strong>お問い合わせ</strong><a href="/ja/consultation">お問い合わせ</a><a href="/ja/resources">考え方・知見</a><a href="/ja/">日本語ホーム</a></div></nav></div><div className="lp-footer-bottom"><p>株式会社Gappy<br />{COMPANY_ADDRESS}</p><span>© 2026 Gappy, Inc.</span></div></div></footer>; }
export default function LandingPage({ variant }: {
    variant: Variant;
}) { return <div className={`lp lp-${variant}`}><Navigation variant={variant}/><main id="main-content" tabIndex={-1}><Hero variant={variant}/><Problem /><Mechanism variant={variant}/><Proof variant={variant}/><GettingStarted /><FAQ /><FinalCTA /></main><Footer /></div>; }
