export type HomeLocale = "en" | "ja";
export const DEMO_URL =
  "https://gappy-workforce-lab-0925.mitsuki222581.chatgpt.site/";
export const workflowIds = [
  "identify",
  "execute",
  "verify",
  "recover",
] as const;

export const homeCopy = {
  en: {
    announcement: "Explore the interactive product demo.",
    viewDemo: "View demo",
    demo: "Start interactive demo",
    sales: "Talk to sales",
    noSignup: "No signup required for this demo.",
    external: "Opens the public demo site",
    synthetic: "Synthetic product demo · No live sends",
    disclaimer:
      "Readiness values illustrate this demo, not customer performance.",
    nav: ["Product", "Workflow", "Technology", "Company", "Resources"],
    company: ["About", "Careers", "Contact"],
    menu: "Menu",
    close: "Close",
    hero: {
      eyebrow: "AI WORKFORCE FOR TRAVEL OPERATIONS",
      title: ["Keep every tour", "ready to operate."],
      body: "Gappy finds what remains after booking, performs the work, and verifies the operational outcome.",
    },
    product: {
      eyebrow: "ONE BOOKING, THROUGH TO READINESS",
      title: ["From one booking", "to verified readiness."],
      body: "Follow a synthetic booking as unresolved work becomes verified readiness.",
    },
    workflow: {
      eyebrow: "THE WORK AFTER BOOKING",
      title: ["Work moves forward.", "Nothing is done until verified."],
      body: "See how Gappy identifies the work, advances it, checks the evidence, and responds to change in this demo.",
    },
    verification: {
      eyebrow: "RESPONSE ≠ VERIFICATION",
      title: ["Replies are not completion."],
      body: "Gappy verifies fresh evidence before treating operational work as done.",
    },
    recovery: {
      eyebrow: "READY IS A CURRENT STATE",
      title: ["When reality changes,", "readiness changes with it."],
      body: "A guide cancellation invalidates the earlier confirmation. Gappy evaluates a replacement and verifies the new evidence before restoring readiness in this demo.",
    },
    context: {
      eyebrow: "OPERATIONAL CONTEXT",
      title: ["The context layer", "for travel operations."],
      body: "Connect the booking, assignments, rules, and evidence around the same operation. The categories below describe operational context, not a list of available integrations.",
    },
    architecture: {
      eyebrow: "DESIGNED AROUND OPERATIONAL CONTROL",
      title: ["Set the boundaries.", "Verify the result."],
      body: "Our design principles: define permitted actions, track the work, verify outcomes, and leave decisions that need judgment with people.",
    },
    proof: {
      eyebrow: "SEE WHAT THE DEMO SHOWS",
      title: ["Inspect the workflow.", "Know what it proves."],
      body: "Explore booking readiness, evidence checks, and recovery in a public synthetic demo. It is not evidence of customer production usage or live integrations.",
    },
    final: {
      eyebrow: "GAPPY AI WORKFORCE",
      title: ["From task automation", "to verified operations."],
      body: "Explore the workflow, then bring us the operation you want to work on.",
    },
    finalDemo: "View interactive demo",
    finalSales: "Talk to Gappy",
    tabs: ["Identify", "Execute", "Verify", "Recover"],
    jobs: [
      [
        "Find what is unresolved.",
        "Turn one booking into an explicit list of requirements.",
      ],
      [
        "Advance the work.",
        "Follow vehicle checks, itinerary resolution, and a received guest response.",
      ],
      [
        "Check the evidence.",
        "A guide reply stays unverified until the required conditions are checked.",
      ],
      [
        "Restore readiness.",
        "Invalidate the old confirmation and evaluate a replacement.",
      ],
    ],
    stages: [
      "Booking received",
      "Work identified",
      "AI Workforce executes",
      "Evidence received",
      "Verification",
      "Tour ready",
    ],
    interim: "Execution stage",
    stage: "Scene",
    ui: {
      readiness: "Tour Readiness",
      requirements: "Operational Requirements",
      activity: "Agent Activity",
      unresolved: "Unresolved",
      evidence: "Evidence",
      verification: "Verification",
      waiting: "Verification pending",
      received: "Response received",
      verified: "Verified",
      invalidated: "Invalidated",
      risk: "At risk",
      resolving: "Resolving",
      ready: "Tour ready",
      recovered: "Tour remains ready",
      nav: ["Today", "Bookings", "Readiness", "Guides", "Reports"],
      tasks: [
        "Guide confirmation",
        "Accessible vehicle",
        "Schedule alignment",
        "Guest communication",
      ],
      statuses: ["Working", "Checked", "Resolved", "Response received"],
      pending: "Pending",
      booking: "Booking details",
      guests: "6 travelers · English",
      place: "Kyoto Station Hachijo Exit",
      needs: "Wheelchair-accessible vehicle",
      updated: "Latest evidence",
      agent: "AI Workforce",
      reply:
        "Confirmed. I can lead the Kyoto Private Tour in English and arrive by 08:40.",
      checks: [
        "Booking & date",
        "Language",
        "Assignment conflict",
        "Required conditions",
        "Evidence freshness",
      ],
      check: "Check evidence",
      checking: "Checking the evidence",
      replay: "Replay",
      principle: "Response received ≠ Verified",
      current: "Every required condition is backed by current evidence.",
      checked: "5 / 5 checks",
      activityItems: [
        "Vehicle verified",
        "Schedule resolved",
        "Guest response received",
      ],
      inspect: "How verification works",
      explore: "Explore recovery",
    },
    recoveryStates: ["Ready", "Change & re-check", "Recovered"],
    recoveryTitles: [
      "Ready to operate.",
      "The old confirmation no longer holds.",
      "Readiness restored.",
    ],
    recoveryBodies: [
      "Every required condition is backed by verified evidence.",
      "A guide cancellation invalidates the earlier evidence. A replacement must be checked.",
      "The replacement guide, latest briefing, and operational requirements have been re-verified.",
    ],
    cancel: "Guide cancellation detected",
    cancelReply: "Sorry, I have a fever and can’t guide tomorrow.",
    candidate: "Replacement guide",
    evaluate: [
      "Qualification",
      "English",
      "Assignment conflict",
      "Compensation policy",
      "Replacement response",
    ],
    evaluateStatus: [
      "Checked",
      "Checked",
      "None",
      "Within policy",
      "Awaiting verification",
    ],
    inputs: [
      "Booking systems",
      "OTA",
      "Email",
      "Chat",
      "Calendar",
      "Policies",
      "Assignments",
      "Traveler details",
    ],
    contextCenter: "Booking · assignments · rules · evidence",
    outputs: [
      "Operational readiness",
      "Items requiring attention",
      "Context for the next decision",
    ],
    controls: [
      ["Permissioned context", "Define what may be accessed and changed."],
      ["Workflow runtime", "Track the operation through its states."],
      ["Outcome verification", "Check the evidence before completion."],
      ["Human control", "Escalate decisions that need judgment."],
    ],
    techLink: "Explore the technology",
    principleNote: "Design principles, not a certification or guarantee.",
    proofs: [
      ["Booking readiness", "Follow unresolved work to a ready state."],
      ["Evidence checks", "Distinguish a received reply from verification."],
      [
        "Recovery",
        "Invalidate the old confirmation and verify the replacement.",
      ],
    ],
    proofLink: "Explore the public demo",
    footer: [
      "Technology",
      "Travel",
      "Projects",
      "Resources",
      "About",
      "Careers",
      "Contact",
    ],
    bookingCta: "Book a demo",
    tagline: "AI Workforce for Travel Operations",
  },
  ja: {
    announcement: "インタラクティブデモを公開中。",
    viewDemo: "デモを見る",
    demo: "インタラクティブデモを見る",
    sales: "相談する",
    noSignup: "このデモは登録なしで体験できます。",
    external: "外部の公開デモサイトへ移動します",
    synthetic: "合成データによる製品デモ・実送信なし",
    disclaimer: "準備率はデモ内の状態を示す値で、顧客の実績値ではありません。",
    nav: ["プロダクト", "業務の流れ", "技術", "会社情報", "考え方・知見"],
    company: ["Gappyについて", "採用情報", "お問い合わせ"],
    menu: "メニュー",
    close: "閉じる",
    hero: {
      eyebrow: "旅行オペレーションのためのAI Workforce",
      title: ["すべてのツアーを、", "催行可能な状態へ。"],
      body: "予約後に残る業務を見つけ、実行し、その結果まで検証します。",
    },
    product: {
      eyebrow: "ひとつの予約を、催行まで",
      title: ["ひとつの予約から、", "根拠のある催行準備へ。"],
      body: "未解決の業務が、証拠で裏付けられた準備完了に変わる流れを、合成データで示します。",
    },
    workflow: {
      eyebrow: "予約後に残る仕事",
      title: ["業務を進める。", "確認できるまで、完了にしない。"],
      body: "業務の特定から実行、証拠の照合、変更への対応まで。デモの中の仕事を追ってください。",
    },
    verification: {
      eyebrow: "返信と検証は、別の状態",
      title: ["返信が来た。", "それだけでは、完了ではない。"],
      body: "日時や条件に合っているか。今も有効な証拠か。業務を完了とする前に、回答を必要な条件と照合します。",
    },
    recovery: {
      eyebrow: "催行準備は、変化し続ける",
      title: ["予定が変われば、", "準備完了も、見直す。"],
      body: "ガイドのキャンセルで、以前の確認は無効に。代替候補を評価し、新しい証拠を照合して、催行可能な状態へ戻します。このデモで、その流れを示します。",
    },
    context: {
      eyebrow: "業務の文脈",
      title: ["予約と、判断の根拠を、", "ひとつの文脈に。"],
      body: "予約、担当、ルール、やり取り、証拠。同じ業務の情報をつなぎ、次の判断に使います。図は情報の種類を示すもので、接続済みサービスの一覧ではありません。",
    },
    architecture: {
      eyebrow: "業務を任せるための設計",
      title: ["任せる範囲を決める。", "結果を確かめる。"],
      body: "許可する操作を定め、進行を追い、結果を検証する。判断が必要な場面は人へつなぐ。Gappyの設計原則です。",
    },
    proof: {
      eyebrow: "デモで確かめる",
      title: ["動きを見て、", "確かめられることを知る。"],
      body: "予約後の業務、証拠の照合、変更からの復旧を、公開デモで確認できます。合成データによるデモであり、顧客の本番運用や実接続の証明ではありません。",
    },
    final: {
      eyebrow: "GAPPY AI WORKFORCE",
      title: ["タスクの自動化から、", "検証された業務へ。"],
      body: "まずは、業務が進む流れを体験。その後、取り組みたい業務をお聞かせください。",
    },
    finalDemo: "インタラクティブデモを見る",
    finalSales: "Gappyに相談する",
    tabs: ["未解決業務の特定", "業務実行", "証拠の検証", "変更からの復旧"],
    jobs: [
      [
        "未解決の業務を見つける。",
        "ひとつの予約から、確認が必要な条件を明らかにします。",
      ],
      [
        "必要な業務を進める。",
        "車両の確認、旅程の整合、顧客からの回答まで、進行を追います。",
      ],
      [
        "証拠を照合する。",
        "ガイドの回答は、必要な条件と照合するまで未確認です。",
      ],
      [
        "催行可能な状態へ戻す。",
        "以前の確認を無効にし、代替候補を評価します。",
      ],
    ],
    stages: [
      "予約受信",
      "未解決業務を特定",
      "業務を実行",
      "回答・証拠を受信",
      "条件を照合",
      "催行可能",
    ],
    interim: "実行の段階",
    stage: "場面",
    ui: {
      readiness: "催行準備率",
      requirements: "催行に必要な業務",
      activity: "エージェント活動",
      unresolved: "未解決",
      evidence: "証拠",
      verification: "照合",
      waiting: "照合待ち",
      received: "回答受信",
      verified: "確認済み",
      invalidated: "確認失効",
      risk: "要対応",
      resolving: "解決中",
      ready: "催行可能",
      recovered: "催行可能な状態を維持",
      nav: ["今日", "予約", "催行準備", "ガイド", "レポート"],
      tasks: ["ガイド確認", "車椅子対応車両", "旅程整合", "顧客連絡"],
      statuses: ["確認中", "確認済み", "解決済み", "回答受信"],
      pending: "未確認",
      booking: "予約詳細",
      guests: "6名・英語対応",
      place: "京都駅八条口",
      needs: "車椅子対応車両",
      updated: "最新の証拠",
      agent: "AI Workforce",
      reply:
        "確認しました。京都のプライベートツアーを英語で案内し、08:40までに到着できます。",
      checks: [
        "予約・日時",
        "言語",
        "重複アサイン",
        "必要な条件",
        "証拠の最新性",
      ],
      check: "証拠を照合",
      checking: "証拠を照合中",
      replay: "もう一度",
      principle: "回答受信 ≠ 確認済み",
      current: "すべての必須条件が、最新の証拠で確認されました。",
      checked: "5 / 5 項目を照合",
      activityItems: ["車両確認を完了", "旅程矛盾を解決", "顧客回答を受信"],
      inspect: "検証の流れを見る",
      explore: "復旧の流れを見る",
    },
    recoveryStates: ["準備完了", "変更と再確認", "復旧完了"],
    recoveryTitles: [
      "催行可能な状態。",
      "以前の確認は、もう有効ではない。",
      "催行可能な状態へ、復旧。",
    ],
    recoveryBodies: [
      "すべての必須条件が、確認済みの証拠で裏付けられています。",
      "ガイドのキャンセルで、以前の証拠は失効。代替候補の確認が必要です。",
      "代替ガイド、最新の引継ぎ情報、全運用要件を再確認しました。",
    ],
    cancel: "ガイドのキャンセルを検知",
    cancelReply: "申し訳ありません。発熱のため、明日のガイドを担当できません。",
    candidate: "代替ガイド候補",
    evaluate: [
      "資格",
      "英語",
      "重複アサイン",
      "報酬・ポリシー",
      "代替ガイドの回答",
    ],
    evaluateStatus: ["確認済み", "確認済み", "なし", "範囲内", "照合待ち"],
    inputs: [
      "予約システム",
      "OTA",
      "メール",
      "チャット",
      "カレンダー",
      "業務ルール",
      "担当・割当",
      "旅行者情報",
    ],
    contextCenter: "予約・担当・ルール・証拠",
    outputs: ["催行準備の状態", "対応が必要な事項", "次の判断に必要な情報"],
    controls: [
      ["許可の範囲", "参照・操作してよい範囲を定める。"],
      ["業務の進行", "状態を追い、次の処理につなぐ。"],
      ["結果の検証", "完了にする前に証拠を照合する。"],
      ["人による判断", "判断が必要な場面を人へつなぐ。"],
    ],
    techLink: "技術と設計を見る",
    principleNote:
      "設計原則の説明であり、認証や性能保証を示すものではありません。",
    proofs: [
      ["催行準備", "未解決の業務が準備完了に至る流れ。"],
      ["証拠の照合", "回答受信と確認済みを区別する流れ。"],
      ["変更からの復旧", "以前の確認を無効にし、代替を再検証する流れ。"],
    ],
    proofLink: "公開デモを体験する",
    footer: [
      "技術",
      "旅行業務",
      "プロジェクト",
      "考え方・知見",
      "Gappyについて",
      "採用情報",
      "お問い合わせ",
    ],
    bookingCta: "デモを予約",
    tagline: "旅行オペレーションのためのAI Workforce",
  },
} as const;

export type HomeCopy = (typeof homeCopy)[HomeLocale];
