import type { JobOpening, SiteContent } from '@/content/en'

const jaOpenings: JobOpening[] = []

export const jaContent = {
  locale: 'ja',
  htmlLang: 'ja',
  ogLocale: 'ja_JP',
  navigation: {
    primary: [
      { label: '旅行業務', path: '/travel' },
      { label: '技術', path: '/technology' },
      { label: '実証', path: '/cases' },
      { label: '会社情報', path: '/about' },
      { label: '採用', path: '/careers' },
    ],
    primaryLabel: 'メインナビゲーション',
    mobileLabel: 'モバイルナビゲーション',
    talk: '業務を相談する',
    openMenu: 'メニューを開く',
    closeMenu: 'メニューを閉じる',
    menuText: 'メニュー',
    closeText: '閉じる',
    skip: '本文へ移動',
  },
  footer: {
    legalName: '株式会社Gappy',
    links: [
      { label: '旅行業務', path: '/travel' },
      { label: '技術', path: '/technology' },
      { label: '実証', path: '/cases' },
      { label: '会社情報', path: '/about' },
      { label: '採用', path: '/careers' },
      { label: 'お問い合わせ', path: '/contact' },
      { label: 'プライバシー', path: '/privacy' },
      { label: 'セキュリティ', path: '/security' },
    ],
    contact: 'お問い合わせ',
    language: '言語',
  },
  common: {
    ctaEyebrow: 'Work with Gappy',
    ctaTitle: 'その業務を、見せてください。',
    ctaBody: '複数のシステム、人の判断、例外対応をまたぎ、今も手作業で進めている重要な業務があれば、ぜひ一度教えてください。',
    ctaPrimary: '業務を相談する',
    ctaSecondary: '会社情報を見る',
  },
  operatingLoop: [
    ['Trigger', '発生を捉える'],
    ['Understand', '状況を理解する'],
    ['Decide', '範囲内で判断する'],
    ['Operate', 'システムを操作する'],
    ['Communicate', '関係者と連携する'],
    ['Verify', '結果を確認する'],
    ['Escalate', '人へ引き継ぐ'],
  ],
  home: {
    seo: {
      title: 'Gappy | 旅行業務を実行するAI Workforce',
      description: 'Gappyは、旅行会社のサプライヤー確認、予約変更、履行確認、顧客連絡などを、既存システムを横断して完了まで実行するAI Workforceを開発しています。',
    },
    hero: {
      eyebrow: 'Gappy / Applied AI',
      title: 'AIが、業務を実行する時代へ。',
      body: 'Gappyは、旅行会社のサプライヤー確認、予約変更、履行確認、顧客連絡などを、既存システムを横断して完了まで実行するAI Workforceを開発しています。',
      emphasis: 'まず、旅行業務から。',
      primary: '旅行業務への取り組みを見る',
      secondary: '業務を相談する',
    },
    trust: ['既存システムを活用', '人による承認', '実行履歴を記録', '完了結果まで確認'],
    what: {
      eyebrow: 'What we build',
      title: '提案するAIから、業務を完了させるAIへ。',
      items: [
        ['システムを横断して操作する', 'メール、予約システム、外部ポータル、CRM、スプレッドシートなど、実際の業務環境を横断して操作します。'],
        ['結果を確認する', '操作しただけで完了とせず、期待する状態と実際の状態を照合し、完了根拠を残します。'],
        ['文脈を保って人へ引き継ぐ', '曖昧さ、権限外、高リスクな判断は、業務履歴と必要な情報を保ったまま人へ引き継ぎます。'],
      ],
    },
    travel: {
      eyebrow: 'Starting with travel',
      title: '最初の実証領域は、旅行オペレーション。',
      body: [
        '旅行業務は複数システムに分断され、サプライヤー、顧客、ガイド、ドライバー、社内担当者を横断します。',
        '時間制約と例外が多いため、AI Workforceの実行能力を検証する厳密な領域です。',
      ],
      workflows: [
        ['Supplier Confirmation', 'サプライヤー確認、再確認、催促、例外対応。'],
        ['Booking Operations', '予約システム、メール、社内キューをまたぐ業務。'],
        ['Changes & Exceptions', '変更やイレギュラーに伴う関連業務の連動。'],
        ['Fulfillment Verification', '提供状況と完了根拠の確認。'],
      ],
      cta: '旅行業務への取り組みを見る',
    },
    work: {
      eyebrow: 'Current work',
      title: '現実の業務から、検証を積み上げる。',
      items: [
        {
          title: 'Gappy Tour Operations',
          subtitle: 'Internal Deployment',
          status: 'INTERNAL / ACTIVE',
          body: 'Gappy自身が運営する旅行業務を対象に、予約、ガイド連携、顧客連絡、出発確認、完了確認を一つの業務フローとして構造化しています。',
        },
        {
          title: 'Founding Design Partner Program',
          subtitle: 'Workflow Co-design',
          status: 'OPEN FOR CONVERSATIONS',
          body: '実際の業務フローを共有し、Offline Evaluation、Shadow、Human-approved executionを通じて、最初の導入範囲を共同で設計する企業との対話を進めています。',
        },
      ],
      cta: '現在の実証を見る',
    },
    technology: {
      eyebrow: 'Technology & accountability',
      title: '業務責任を担えるように、権限と完了条件を設計する。',
      body: '業務責任には、モデル性能だけでなく、明確な権限範囲、人による統制、実行履歴、そして検証可能な完了条件が必要です。',
      items: [
        ['Permission Boundaries', 'アクセス、判断、変更できる範囲を定義します。'],
        ['Human Approval', '重要、曖昧、ルール外の判断を人の統制下に置きます。'],
        ['Execution Trace', '文脈、操作、承認、引き継ぎ、実際の状態を記録します。'],
        ['Verified Completion', '期待する状態と実際の状態を照合してから完了とします。'],
      ],
      cta: '技術設計を見る',
    },
    company: {
      eyebrow: 'Company',
      title: 'AI、Software、Product、Travel Operationsを横断する。',
      body: 'Gappyは、AI、Software、Product、Travel Operationsを横断し、現実の業務で責任を担えるAIシステムを開発しています。',
      name: '浅野 充輝 / Mitsuki Asano',
      role: '株式会社Gappy 代表取締役',
      cta: '会社情報を見る',
    },
    careers: {
      eyebrow: 'Careers',
      title: 'Open Application',
      status: '現在公開中のポジションはありません。',
      body: 'GappyのMissionに強く共感し、自分ならではの専門性で貢献したい方からのOpen Applicationは受け付けています。',
      cta: '採用情報を見る',
    },
  },
  technology: {
    seo: {
      title: '技術設計 | Gappy AI Workforce',
      description: 'Gappyが権限範囲、人による承認、既存システム操作、実行履歴、完了確認、エスカレーションをどう設計するか。',
    },
    hero: {
      eyebrow: 'Technology',
      title: '業務責任を、明確な統制のもとで。',
      body: ['Gappyは、Workflowごとに権限、アクセス、根拠、完了条件を設計します。', 'Human Escalationは、すべてのレイヤーを横断します。'],
    },
    loop: {
      eyebrow: 'Operating loop',
      title: '発生から、検証された完了まで。',
      body: '各段階で得た文脈と制約を次へ引き継ぎます。人へのエスカレーションも、業務モデルの一部です。',
    },
    layers: [
      { eyebrow: 'Context', title: 'ルールと業務状態を理解する。', body: '操作を検討する前に、記録、メッセージ、ルール、履歴、例外を揃えます。', detail: ['Policy and context', 'Workflow state', '記録とメッセージ'] },
      { eyebrow: 'Authority', title: '実行できる範囲を限定する。', body: '権限、承認条件、リスク境界により、AIが動ける範囲と人が判断する範囲を定義します。', detail: ['Permission boundary', 'Human approval', 'Risk limits'] },
      { eyebrow: 'Execution', title: '許可されたアクセスで操作する。', body: '承認されたシステムアクセスを用い、操作と引き継ぎの履歴を残します。', detail: ['System access', 'Execution history', '文脈を保った引き継ぎ'] },
      { eyebrow: 'Verification', title: '根拠をもってループを閉じる。', body: '期待する状態と実際の状態を照合し、根拠が確認できたときだけ完了とします。', detail: ['Expected state', 'Actual state', 'Evidence'], statement: 'Action ≠ Completion' },
    ],
    humanEscalation: {
      eyebrow: 'Across every layer',
      title: '文脈を保って、人へ引き継ぐ。',
      body: '曖昧さ、ルール外、権限不足、高リスクな判断は、業務状態と実行履歴を保ったまま適切な人へ引き継ぎます。',
    },
    principles: {
      eyebrow: 'Control model',
      title: '実行根拠が確認できた範囲だけ、責任を広げる。',
      items: [
        ['Scoped Authority', '実行前に、許可された判断と操作を定義する。'],
        ['Traceability', '文脈、操作、承認、確認結果を記録する。'],
        ['Human Escalation', '不確実性を判断に必要な情報とともに人へ戻す。'],
        ['Progressive Autonomy', '実際の根拠が支持する範囲だけ責任を広げる。'],
      ],
    },
    cta: { body: '実際のシステム、制約、例外、完了条件を持つWorkflowを見せてください。まず、業務の現実を可視化します。' },
  },
  travel: {
    seo: {
      title: '旅行業務のAI Workforce | Gappy',
      description: 'Gappyは、サプライヤー確認、予約業務、変更、履行確認、顧客連絡を既存の旅行システムを横断して実行します。',
    },
    hero: {
      eyebrow: 'Gappy / Travel',
      title: '旅行業務のAI Workforce',
      body: '予約システム、メール、Supplier Portal、CRM、Spreadsheet、人の判断を横断する旅行業務のためのOperational AIです。',
      primary: '旅行業務を相談する',
      secondary: '現在の実証を見る',
    },
    why: {
      eyebrow: 'Why travel',
      title: '旅行業務は、システムとシステムの間に残っている。',
      body: ['予約情報が一つのシステムに記録されても、旅行の提供にはサプライヤー連絡、変更処理、履行確認、社内キュー、顧客対応が続きます。', 'Gappyは、この調整レイヤーを対象にしています。'],
    },
    target: {
      eyebrow: 'Who we are building with',
      title: '現在の重点領域と、長期的な適用範囲を分ける。',
      currentLabel: '現在の重点領域',
      current: ['Inbound Tour Operators', 'DMCs', 'Travel Operations Teams'],
      longerTermLabel: '長期的な適用範囲',
      longerTerm: ['TMCs', 'OTAs', 'Large Travel Groups'],
    },
    workflows: {
      eyebrow: 'Travel workflows',
      title: 'チームが今も担っている業務から始める。',
      labels: ['Trigger', 'Systems', 'Human control', 'Complete when'],
      items: [
        { title: 'サプライヤー対応', body: '予約確認、再確認、催促、例外対応をSupplier Channel横断で実行します。', trigger: '出発日・提供日が近づく', systems: '予約システム / Email / Supplier Portal', humanControl: '例外対応の承認', completeWhen: 'Supplier Statusが確認・記録される' },
        { title: '予約オペレーション', body: 'メール、予約システム、社内キューをまたぐ予約業務を進めます。', trigger: '新規予約・変更依頼', systems: 'Inbox / Booking System / Internal Queue', humanControl: '商務・ルール例外', completeWhen: '必要な予約状態が確認される' },
        { title: '照合・精算', body: '照合、差分確認、必要なフォローアップを追跡可能にします。', trigger: '請求・支払情報を受領', systems: 'Spreadsheet / 予約記録 / 会計ツール', humanControl: '重要な差分の承認', completeWhen: '差分が解消または担当者へ割り当てられる' },
        { title: '予約QA・履行確認', body: '予約内容と提供状況を確認し、未解決の例外を明確にします。', trigger: '出発前・提供時のCheckpoint', systems: '予約システム / Operations Tracker / Email', humanControl: '未解決の履行リスク', completeWhen: '提供根拠が確認される' },
        { title: '変更・イレギュラー対応', body: '時刻やサービス変更に伴う下流業務を連動させます。', trigger: 'Schedule・Service変更を検知', systems: 'Supplier Channel / CRM / Booking System', humanControl: '代替案の選択と承認', completeWhen: '影響する記録と関係者が更新される' },
        { title: '顧客コミュニケーション', body: '業務フローの一部として、文脈に沿った連絡を実行します。', trigger: '確認済みの更新に連絡が必要', systems: 'CRM / Email / Messaging', humanControl: '重要・例外的なメッセージ', completeWhen: '承認内容と送信状態が記録される' },
      ],
    },
    systems: {
      eyebrow: 'Existing systems',
      title: '既存システムは、そのまま。',
      statement: '変えるのは、人が担っている調整レイヤー。',
      items: ['Email', 'CRM', 'GDS', 'Excel / Spreadsheet', 'Supplier Portal', 'Booking System', 'Internal System', 'Messaging'],
    },
    deployment: {
      eyebrow: 'Start bounded',
      title: 'まず、一つの業務から。',
      steps: [
        ['Map', 'Trigger、システム、判断、例外、完了条件を定義します。'],
        ['Offline Evaluation', '代表的な過去事例でWorkflowを評価します。'],
        ['Shadow', '業務権限を持たず、実際の作業を観察します。'],
        ['Human-approved', '人の承認下で実行し、根拠と例外を測ります。'],
      ],
    },
    measurement: {
      eyebrow: 'Measurement',
      title: '操作回数ではなく、業務完了を測る。',
      body: '基準値と成功条件はWorkflowごとに定義します。ここでは未検証の性能を主張しません。',
      items: ['Verified Completion', 'Human Intervention', '手戻り', '処理時間', '重大エラー', '例外率'],
    },
    cta: {
      title: 'まず、一つの旅行業務から。',
      body: 'Trigger、利用システム、例外、完了条件を見せてください。最初の検証で何を確かめるかを定義します。',
      secondary: '現在の実証を見る',
    },
  },
  projects: {
    seo: { title: '現在の実証 | Gappy', description: 'Gappyが自社旅行業務と段階的なDesign Partner Pathを通じてAI Workforceを検証する方法。' },
    hero: {
      eyebrow: 'Current work and validation',
      title: '現実の業務から、検証を積み上げる。',
      body: 'Gappyは、Feature Listからではなく、実際に発生している業務、利用システム、判断、例外、完了条件からAI Workforceを設計します。',
    },
    works: [
      {
        title: 'Gappy Tour Operations', subtitle: 'Internal Deployment', status: 'INTERNAL / ACTIVE',
        body: 'Gappy自身の旅行業務を最初の環境として、予約、ガイド連携、顧客連絡、出発確認、完了確認を一つのWorkflowとして構造化しています。',
        details: [
          ['対象業務', '予約、ガイド連携、顧客連絡、出発確認、完了確認'],
          ['現在の検証範囲', 'Workflow定義、業務状態、引き継ぎ、完了根拠'],
          ['人が担う判断', '例外、ルール判断、重要なコミュニケーション'],
          ['完了条件', '必要な旅行状態と根拠が記録されていること'],
        ],
      },
      {
        title: 'Founding Design Partner Program', subtitle: 'Workflow Co-design', status: 'OPEN FOR CONVERSATIONS',
        body: '実際のWorkflowを共有し、Gappyと最初の検証範囲を定義する企業のための段階的な進め方です。',
        details: [
          ['共有してもらうもの', '現在のWorkflow、システム、判断、例外、完了条件'],
          ['最初の定義', '権限と根拠が明確な一つのWorkflow'],
          ['検証方法', 'Offline Evaluation、Shadow、Human-approved Execution'],
          ['拡張', '実行根拠が支持する範囲だけLimited Autonomyへ進む'],
        ],
      },
    ],
    evaluation: { eyebrow: 'Evaluation path', title: '自律範囲は、根拠のあとに広げる。', steps: ['Offline Evaluation', 'Shadow', 'Human-approved Execution', 'Limited Autonomy'] },
    evidence: { eyebrow: 'Evidence policy', title: '検証可能な根拠だけを公開する。', body: '顧客名、処理件数、削減率、成果数値は、公開承認と検証可能な根拠がある場合だけ掲載します。' },
    cta: { title: '一つのWorkflowを、一緒に定義する。', body: '現実の業務から始め、最初の検証で何を証明するかを定義します。', secondary: '旅行業務を見る' },
  },
  insights: {
    seo: { title: 'Gappy Research Notes | 日本語', description: 'AI Workforce、Travel Operations、Human Control、Verified Completionについて、今後公開するGappyの実務ノート。' },
    hero: { eyebrow: 'Research notes', title: 'Gappy Research Notes', body: 'AI Workforce、Travel Operations、Human Control、Verified Completionについて、実務から得た知見を順次公開します。' },
    note: '現在、公開中の記事はありません。',
  },
  about: {
    seo: { title: '会社情報 | Gappy', description: 'Gappyは、旅行業務を起点に現実のオペレーションで責任を担えるAI Workforceを開発する日本のApplied AI Companyです。' },
    hero: { eyebrow: 'About Gappy', title: '業務責任を担えるAIをつくる。', body: ['Gappyは、Softwareと人を横断する現実の業務のためにAIシステムを開発しています。', '現在の重点領域は、旅行オペレーションです。'] },
    mission: { eyebrow: 'Mission', title: '複雑な業務を、自律的に。', body: ['企業はこれまで何十年もかけて情報をデジタル化してきました。', '次に起きるのは、実行そのもののデジタル化です。', '人が方針、曖昧さ、リスクをコントロールしながら、AIが一定の業務責任を担えるシステムをGappyはつくります。'] },
    why: { eyebrow: 'Why now', title: 'AIによって、ソフトウェアが担える責任が変わる。', body: ['従来のソフトウェアは、人が操作することを前提としていました。', '現代のAIは、非構造化情報を理解し、複数のInterfaceを操作し、制約の中で判断できます。', '重要なのは、すべての画面にAI Assistantを付けることではありません。', '業務そのものの進み方を再設計することです。'] },
    principles: {
      eyebrow: 'Principles', title: '現実の業務から、外側へ広げる。',
      items: [
        ['現実の業務から始める', '自動化を決める前に、業務が実際にどう動くかを確認する。'],
        ['Outcomeまで責任を持つ', '孤立した操作ではなく、検証された完了を設計する。'],
        ['現実の制約で動く', '既存システム、ルール、権限、例外を前提にする。'],
        ['根拠をもとに広げる', '実際の結果が支持する範囲だけ責任を広げる。'],
      ],
    },
    founder: {
      eyebrow: 'Founder', title: 'オペレーションは、ソフトウェアと現実が交わる場所。',
      body: ['本当に重要な業務の多くは、一つのきれいな画面の中だけでは完結しません。', '人、システム、メッセージ、判断、例外の間を移動しながら進みます。', 'Gappyは、その現実の中で実際に動けるAIをつくるために存在します。'],
      name: '浅野 充輝 / Mitsuki Asano', role: '株式会社Gappy 代表取締役', imageAlt: '株式会社Gappy 代表取締役 浅野充輝',
    },
    timeline: { eyebrow: 'Company timeline', title: '確認できる歩み。', items: [['2025', '株式会社Gappy設立'], ['2026', 'AI Workforce for Travel Operationsを重点領域として開発']] },
    team: { eyebrow: 'Team', title: 'Founder-led Company', body: 'Gappyは現在、Founderが率いる小さな会社です。その他のメンバーは、氏名、役職、公開承認を確認できた場合だけ掲載します。' },
    company: { eyebrow: 'Company information', labels: ['会社名', '代表者', '設立', '所在地', '連絡先'] },
  },
  careers: {
    seo: { title: '採用情報 | Gappy', description: '現実の業務で責任を担えるAIシステムを開発するGappyの採用情報とOpen Application。' },
    hero: { eyebrow: 'Careers', title: '現実の業務で動くAIをつくる。', body: ['私たちがつくるのは、文章を生成して終わるAIではありません。', 'AIの能力を、現実の権限、操作、例外、結果へ接続する仕事です。'] },
    currentOpenings: { eyebrow: 'Current openings', title: 'Open Application', empty: '現在、公開中のポジションはありません。', body: 'GappyのMissionに強く共感し、自分ならではの専門性で貢献したい方からのOpen Applicationは受け付けています。' },
    openings: jaOpenings,
    disciplines: { eyebrow: 'Disciplines we work across', title: '業務を実行するAIを支える専門性。', body: '以下はGappyで扱う専門領域であり、現在の求人一覧ではありません。', items: ['AI / Agent Engineering', 'Full-stack Engineering', 'Product', 'Design', 'Travel Operations', 'Business Development'] },
    principles: [
      ['最先端技術を、現実の業務へ', 'AIの能力を、操作、権限、結果に責任が伴う業務へつなげます。'],
      ['業務に近い場所でつくる', '人、システム、例外、判断そのものから学びます。'],
      ['高いOwnership', '小さなチームが課題設定から実行根拠までを担います。'],
    ],
    application: { primary: 'Open Applicationを送る', secondary: '会社情報を見る' },
  },
  contact: {
    seo: { title: 'お問い合わせ | Gappy', description: '旅行業務のWorkflow相談、採用、投資、メディア、協業、会社に関するお問い合わせ。' },
    hero: { eyebrow: 'Contact', title: 'その業務を、見せてください。', body: '複数のシステム、人、例外をまたぎ、今も手作業で動く重要な業務があれば、ぜひ一度教えてください。' },
    paths: [
      { title: 'Workflow / Design Partner', body: '現在の業務フロー、利用システム、例外、人への引き継ぎ、最初に検証すべき完了条件を整理します。', note: '外部の予約サービスへ移動します。', cta: '業務相談を予約する' },
      { title: 'General Contact', body: '採用、投資、メディア、協業、その他の会社に関するお問い合わせは、メールでご連絡ください。', note: 'このWebsiteの直接の連絡方法はEmailです。', cta: 'メールで問い合わせる' },
    ],
  },
  privacy: {
    seo: { title: 'プライバシー | Gappy', description: 'GappyのCorporate Websiteと外部の問い合わせ導線における情報の取り扱い。' },
    hero: { eyebrow: 'Privacy', title: 'プライバシーについて', body: 'GappyのCorporate Websiteに現在存在する、限定的な情報の流れを説明します。' },
    updated: '最終更新日：2026年8月26日',
    sections: [
      ['提供いただく情報', ['本Websiteは、Emailでの問い合わせと外部予約サービスへのLinkを提供します。これらのServiceを通じて送信する情報は、利用者自身が提供するものです。']],
      ['利用目的', ['問い合わせへの回答、会話の日程調整、協業可能性の検討、必要な事業記録の維持に使用する場合があります。']],
      ['AnalyticsとCookie', ['現在のWebsite Codeには、Analyticsまたは広告Trackingの設定はありません。Hosting Providerや外部Serviceが、それぞれのPolicyに基づいてTechnical DataやCookieを扱う場合があります。']],
      ['外部Service', ['日程調整Linkは外部Serviceへ移動します。Email配信とWebsite HostingにもService Providerが関与します。情報を提供する前に、各Serviceに表示されるPolicyを確認してください。']],
      ['第三者提供と保持', ['本Websiteでは固定の保持期間を定めていません。問い合わせ対応、法令、安全性、事業記録に合理的に必要な範囲で保持し、Service Providerまたは法令上必要な場合に共有することがあります。']],
      ['お問い合わせ', ['本Noticeに関する質問は、下記のContact Emailへお送りください。']],
    ],
  },
  security: {
    seo: { title: 'セキュリティ設計 | Gappy', description: '権限範囲、人による承認、実行履歴、完了確認、エスカレーション、段階的Pilotに関するGappyの設計方針。' },
    hero: { eyebrow: 'Security', title: '自律化の前に、統制を設計する。', body: 'Gappyは、権限、承認、根拠、エスカレーションを、BadgeではなくWorkflow設計の一部として扱います。' },
    notice: 'このページは設計方針とPilot方法を説明するもので、Security認証の取得を主張するものではありません。',
    sections: [
      ['限定された権限範囲', '合意した検証に必要なシステムとWorkflowだけに、アクセスと操作を限定します。'],
      ['Human Approval', '重要、曖昧、ルールに関わる操作は、人の確認対象とします。'],
      ['Execution Logging', '関連する文脈、操作、承認、引き継ぎを追跡できるよう設計します。'],
      ['Completion Verification', '期待する状態と実際の状態を照合してから完了とします。'],
      ['Escalation', '権限不足、曖昧さ、ルール例外、リスクを、文脈とともに人へ引き継ぎます。'],
      ['段階的なPilot', 'Offline Evaluation、Shadow、Human-approved Executionを経て、根拠が支持する場合だけLimited Autonomyへ進みます。'],
    ],
  },
} satisfies SiteContent
