export const globalTravelContent = {
  hero: {
    eyebrow: 'AI Workforce for Post-Booking Travel Operations',
    title: ['Every booking confirmed.', 'Exceptions handled.'],
    body:
      'Gappy monitors every booking, coordinates guides and suppliers, follows up until they respond, verifies the latest booking state, and escalates only what needs a human.',
    primary: 'See it work on a booking',
    secondary: 'Start a Shadow Pilot',
  },
  operatorDay: [
    ['09:00', "Check tomorrow's bookings"],
    ['09:10', 'Find unconfirmed guides'],
    ['09:20', 'Contact guides and suppliers'],
    ['12:00', 'Check replies'],
    ['15:00', 'Chase non-responders'],
    ['17:30', 'Detect a booking change'],
    ['17:40', 'Reconfirm'],
    ['18:00', "Review tomorrow's exceptions"],
  ],
  before: ['Booking', 'Find task', 'Contact', 'Wait', 'Check', 'Chase', 'Update', 'Check again'],
  after: ['Booking', 'Detect', 'Decide', 'Execute', 'Chase', 'Verify'],
  workflow: [
    ['01', 'Detect', 'A booking enters the confirmation window.'],
    ['02', 'Understand', 'Current booking, guide, supplier, and policy context are assembled.'],
    ['03', 'Decide', 'Gappy determines what must happen next.'],
    ['04', 'Approve when needed', 'A human reviews actions that sit outside the approved boundary.'],
    ['05', 'Execute', 'The right guide or supplier is contacted.'],
    ['06', 'Chase', 'Non-responses stay in the queue until the deadline.'],
    ['07', 'Verify', 'The reply is checked against the latest booking state.'],
    ['08', 'Escalate', 'Uncertainty reaches a person with the relevant context.'],
  ],
  controlRoom: [
    ['Bangkok Highlights', 'Tomorrow · 08:30', 'Somsak', 'NEEDS APPROVAL', 'Review outreach', '46 min'],
    ['Seoul Evening Food Tour', 'Tomorrow · 18:00', 'Min-jun', 'WAITING', 'Follow up at 15:00', '3 hr'],
    ['Mt. Fuji Day Tour', 'Tomorrow · 10:30', 'Tanaka', 'RECONFIRMATION', 'Confirm new time', '28 min'],
    ['Bali Temple Trail', 'Fri · 07:00', 'Supplier desk', 'ESCALATED', 'Resolve conflict', 'Now'],
    ['Taipei Market Walk', 'Fri · 10:00', 'Mei', 'VERIFIED', 'No action', 'Complete'],
  ],
  systemClasses: [
    'Booking systems',
    'Email',
    'Messaging channels',
    'Spreadsheets',
    'Supplier portals',
    'Internal systems',
    'APIs and webhooks',
  ],
  autonomy: [
    ['Shadow', 'Observe real cases without sending externally.'],
    ['AI Recommendation', 'Show the next action and supporting reason.'],
    ['Human-approved', 'Execute after an operator confirms the action.'],
    ['Limited Autonomous', 'Act inside an agreed policy boundary.'],
    ['Autonomous', 'Expand only where operating evidence supports it.'],
  ],
  failClosed: ['Unknown state', 'Stale data', 'Conflicting state', 'Sync failure', 'Missing evidence'],
  trust: [
    ['Human approval', 'Keep people in the loop where authority or risk requires it.'],
    ['Scoped operation', 'Define what the workforce may decide and execute during a pilot.'],
    ['Traceable work', 'Keep the booking context, recommendation, action, and observed result together.'],
    ['Fail-closed verification', 'Escalate when completion cannot be supported by current evidence.'],
    ['Tenant-aware boundaries', 'Keep operator context and brand behavior separated by tenant.'],
  ],
  pilotStages: [
    ['01', 'Operations Review', 'Map the workflow, systems, deadlines, and exceptions.'],
    ['02', 'Offline Evaluation', 'Compare Gappy against historical operational cases.'],
    ['03', 'Shadow Mode', 'Process real cases without sending externally.'],
    ['04', 'Human-approved Execution', 'Let operators approve each external action.'],
    ['05', 'Limited Autonomous Execution', 'Expand authority only where evidence justifies it.'],
  ],
  whiteLabel: ['Your brand', 'Your operating rules', 'Your market', 'One shared runtime'],
  metrics: [
    'Verified Completion Rate',
    'Human Touch Rate',
    'Time to Verified Completion',
    'Unconfirmed Bookings at Deadline',
    'Escalation Rate',
    'Reconfirmation Rate',
    'Human Minutes per Booking',
    'Cost per Verified Completion',
    'Major Errors',
  ],
  expansion: ['Schedule Change', 'Booking QA', 'Cancellation / Refund', 'Reconciliation', 'Customer Communication'],
} as const
